<h2>Login using this form</h2>
<?php echo $this->tag->linkTo("signup","Sign Up User") ?>
<?php echo $this->tag->form('login') ?>
<div class=”flash-message-css”>
<?php if(isset($message))
	echo "<div class='alert alert-error'>".$message."</div>";
?>
</div>
	<p>
		<label for="name">E-Mail</label>
		<?php echo $this->tag->textField("email") ?>
	</p>

	<p>
		<label for="password">Password</label>
		<?php echo $this->tag->passwordField("password") ?>
	</p>

	<p>
		<?php echo $this->tag->submitButton("Login") ?>
	</p>

</form>
